[package]
name = "moyai-bot"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/getchoo/moyai-bot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bottomify = "1.2.0"
dotenvy = "0.15.7"
env_logger = "0.11.6"
log = "0.4.25"
poise = "0.6.1"
rand = "0.9.0"
redis = { version = "0.28", features = ["tokio-comp", "tokio-rustls-comp"] }
redis-macros = "0.5"
reqwest = { version = "0.12.12", default-features = false, features = [
	"rustls-tls",
	"json",
] }
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = [
	"macros",
	"rt-multi-thread",
	"signal",
] }
url = { version = "2.5.4", features = ["serde"] }
uwurandom-rs = "1.1.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
complexity = "warn"
correctness = "deny"
pedantic = "warn"
perf = "warn"
style = "warn"
suspicious = "deny"
